export enum PaginaStatus {
  ATIVA = 'ATIVA',
  INATIVA = 'INATIVA',
  SUSPEITA = 'SUSPEITA',
}

export enum ScanStatus {
  PENDENTE = 'PENDENTE',
  PROCESSANDO = 'PROCESSANDO',
  CONCLUIDO = 'CONCLUIDO',
  ERRO = 'ERRO',
}

export enum Tendencia {
  SUBINDO = 'SUBINDO',
  NEUTRO = 'NEUTRO',
  CAINDO = 'CAINDO',
}

export enum AlertaTipo {
  NOVA_OFERTA = 'NOVA_OFERTA',
  SCORE_ALTO = 'SCORE_ALTO',
  TENDENCIA_ALTA = 'TENDENCIA_ALTA',
  PAGINA_NOVA = 'PAGINA_NOVA',
  LANCAMENTO_DETECTADO = 'LANCAMENTO_DETECTADO',
}
